name: CDK Diff
description: Diff two cdk.out directories
inputs:
  base:
    description: The cdk.out directory of the baseline or current synth
    required: true
    default: base.cdk.out
  head:
    description: The cdk.out directory of the new synth
    required: true
    default: head.cdk.out
  enable-comments:
    description: Whether to create a comment on the pull request with the diff output
    required: false
    default: "false"
  ignore-keys:
    description: ->
      A comma-separated list of JSON/YAML keys to ignore in the diff output. Nested keys are supported using dot notation (e.g.,
      'Code.S3Key' will ignore any 'S3Key' properties that are nested under a 'Code' object).
    required: false
  rename:
    description: Rename base and head on copy instead of maintaining directory names - set to any value to enable
    required: false
outputs:
  has_diff:
    description: Has the value of 0 if no differences found or 1 if differences found
    value: ${{ steps.diff.outputs.diff }}
  comment_file:
    description: A file with markdown that contains details about the diff
    value: ${{ steps.diff.outputs.comment_file }}
  diff_file:
    description: A file that contains the unaltered diff output
    value: ${{ steps.diff.outputs.diff_file }}
runs:
  using: "composite"
  steps:
    - name: Install rain
      run: ${{ github.action_path }}/install_rain.sh
      shell: bash
    - name: CDK diff
      id: diff
      run: ${{ github.action_path }}/cdk_diff.sh ${{ inputs.base }} ${{ inputs.head }}
      shell: bash
      env:
        CDK_DIFF_IGNORE_KEYS: "${{ inputs.ignore-keys }}"
        CDK_DIFF_RENAME: "${{ inputs.rename }}"
        CDK_DIFF_ENABLE_COMMENTS: "${{ inputs.enable-comments }}"
