name: CDK Diff
description: Diff two cdk.out directories
inputs:
  base:
    description: The cdk.out directory of the baseline or current synth
    required: true
    default: base.cdk.out
  head:
    description: The cdk.out directory of the new synth
    required: true
    default: head.cdk.out
  allow-destruction-of:
    description: A list of resources that are allowed to be destroyed. This is a comma-separated list of resource logical IDs.
    required: false
  fail-on-destructive-changes:
    description: If true, the action will fail if any destructive changes are found in the diff.
    required: false
    default: "true"
  summarize:
    description: If true, the action will summarize the diff output via a special PR comment. This is useful for large diffs.
    required: false
    default: "true"
  ignore-changes:
    description: A list of resources that are ignored in the diff. This is a comma-separated list of resource logical IDs.
    required: false
  ignore-asset-only-changes:
    description: If true, the action will ignore changes to assets in the diff. This is useful for large diffs.
    required: false
    default: "false"
outputs:
  has_diff:
    description: Has the value of 0 if no differences found or 1 if differences found
  comment_file:
    description: A file with markdown that contains details about the diff
  diff_file:
    description: A file that contains the unaltered diff output
runs:
  using: "node20"
  main: "src/index.mjs"