name: CDK Diff
description: Diff two cdk.out directories
inputs:
  github-token:
    description: The GitHub token to use for the action. This token is automatically created by GitHub and does not require any configuration.
    required: true
  base:
    description: The cdk.out directory of the baseline or current synth
    required: true
    default: base.cdk.out
  head:
    description: The cdk.out directory of the new synth
    required: true
    default: head.cdk.out
  disable-comments:
    description: If true, the action will not create a comments on the PR.
    required: false
    default: "false"
  disable-labels:
    description: If true, the action will not create labels on the PR.
    required: false
    default: "false"
  disable-summary:
    description: If true, the action will not summarize the diff output via a special PR comment.
    required: false
    default: "false"
  ignore-changes:
    description: A list of resources that are ignored in the diff. This is a comma-separated list of resource logical IDs.
    required: false
    default: "false"
  ignore-asset-only-changes:
    description: If true, the action will ignore changes to assets in the diff. This is useful for large diffs.
    required: false
    default: "false"
outputs:
  has-changes:
    description: Has the value of false if no differences found or true if differences found
    value: steps.cdk-diff.outputs.has-changes
  has-destructive-changes:
    description: Has the value of false if no differences found or true if differences found
    value: steps.cdk-diff.outputs.has-destructive-changes
  has-security-group-changes:
    description: Has the value of false if no differences found or true if differences found
    value: steps.cdk-diff.outputs.has-security-group-changes
  has-iam-changes:
    description: Has the value of false if no differences found or true if differences found
    value: steps.cdk-diff.outputs.has-iam-changes
runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      shell: bash
      run: |
        npm ci
        npm install -g ts-node typescript

    - name: Run CDK Diff
      id: cdk-diff
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        BASE_PATH: ${{ inputs.base }}
        HEAD_PATH: ${{ inputs.head }}
        DISABLE_COMMENTS: ${{ inputs.disable-comments }}
        DISABLE_LABELS: ${{ inputs.disable-labels }}
        DISABLE_SUMMARY: ${{ inputs.disable-summary }}
        IGNORE_CHANGES: ${{ inputs.ignore-changes }}
        IGNORE_ASSET_CHANGES: ${{ inputs.ignore-asset-only-changes }}
      run: ts-node src/index.ts