name: CD Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install yq
        run: ./install_yq.sh

      - name: Unit tests
        run: make

  action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run action
        id: diff
        uses: ./
        with:
          base: test/fixtures/base.cdk.out
          head: test/fixtures/head.cdk.out

      - name: Test comment file exists
        run: test -f ${{ steps.diff.outputs.comment_file }}

      - name: Print comment file
        run: cat ${{ steps.diff.outputs.comment_file }}

      - name: Test has_diff = 1
        run: test "${{ steps.diff.outputs.has_diff }}" = "1"

  cd:
    needs: [test, action]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Version
        id: version
        uses: Class-Foundations/gh-action-version-cat@v2

      - name: Create Release ${{ steps.version.outputs.version }}
        if: github.event_name == 'push'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.version }}
          release_name: ${{ steps.version.outputs.version }}

      - name: Checkout ${{ steps.version.outputs.version }}
        if: github.event_name == 'push'
        uses: actions/checkout@v2
        with:
          ref: ${{ steps.version.outputs.version }}
          fetch-depth: 0

      - name: Tag and Push v${{ steps.version.outputs.major }}
        if: github.event_name == 'push'
        run: |
          git tag -f v${{ steps.version.outputs.major }}
          git push -f origin v${{ steps.version.outputs.major }}