name: CD Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  GIT_AUTHOR_NAME: github-actions[bot]
  GIT_AUTHOR_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
  GIT_COMMITTER_NAME: GitHub
  GIT_COMMITTER_EMAIL: noreply@github.com

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install yq
        run: ./install_yq.sh

      - name: Unit tests
        run: make

  action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run action
        id: diff
        uses: ./
        with:
          base: test/fixtures/base.cdk.out
          head: test/fixtures/head.cdk.out

      - name: Test comment file exists
        run: test -f ${{ steps.diff.outputs.comment_file }}

      - name: Print comment file
        run: cat ${{ steps.diff.outputs.comment_file }}

      - name: Test has_diff = 1
        run: test "${{ steps.diff.outputs.has_diff }}" = "1"

  cd:
    needs: [test, action]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Version
        id: version
        uses: blackboard-innersource/gh-action-version-cat@v2

      - name: Create Release ${{ steps.version.outputs.version }}
        if: github.event_name == 'push'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ steps.version.outputs.version }} \
            --title ${{ steps.version.outputs.version }} \
            --target ${{ github.sha }}

      - name: Checkout ${{ steps.version.outputs.version }}
        if: github.event_name == 'push'
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.version.outputs.version }}
          fetch-depth: 0

      # https://github.com/actions/toolkit/blob/master/docs/action-versioning.md
      - name: Tag and Push v${{ steps.version.outputs.major }}
        if: github.event_name == 'push'
        run: |
          git tag -fa v${{ steps.version.outputs.major }} -m "Update v${{ steps.version.outputs.major }} tag"
          git push origin v${{ steps.version.outputs.major }} --force